version: '3.9'

services:
  # -----------------------------------------------
  # API Gateway
  # -----------------------------------------------
  gateway:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - foodfast-net
    depends_on:
      - users
      - products
      - orders
      - payments

  # -----------------------------------------------
  # Database
  # -----------------------------------------------
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1444:1433"
    networks:
      - foodfast-net

  # -----------------------------------------------
  # Users Service
  # -----------------------------------------------
  users:
    build: ./users
    container_name: users_service
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      USERS_DB: ${USERS_DB}
    depends_on:
      - sqlserver
    networks:
      - foodfast-net

  # -----------------------------------------------
  # Products Service
  # -----------------------------------------------
  products:
    build: ./products
    container_name: products_service
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PRODUCTS_DB: ${PRODUCTS_DB}
    depends_on:
      - sqlserver
    networks:
      - foodfast-net

  # -----------------------------------------------
  # Orders Service
  # -----------------------------------------------
  orders:
    build: ./orders
    container_name: orders_service
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ORDERS_DB: ${ORDERS_DB}
      USERS_BASE: "http://users_service:5001"
      PRODUCTS_BASE: "http://products_service:5002"
    depends_on:
      - sqlserver
      - users
      - products
    networks:
      - foodfast-net

  # -----------------------------------------------
  # Payments Service
  # -----------------------------------------------
  payments:
    build: ./payments
    container_name: payments_service
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PAYMENTS_DB: ${PAYMENTS_DB}
    depends_on:
      - sqlserver
      - orders
    networks:
      - foodfast-net

networks:
  foodfast-net:
    driver: bridge
