version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: localhost
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1444:1433"
    networks:
      - foodfast-net

  users:
    build: ./users
    container_name: users_service
    environment:
      DB_HOST: localhost
      DB_PORT: 1433
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${USERS_DB}
    ports:
      - "${USERS_PORT}:5001"
    depends_on:
      - sqlserver
    networks:
      - foodfast-net

  products:
    build: ./products
    container_name: products_service
    environment:
      DB_HOST: localhost
      DB_PORT: 1433
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${PRODUCTS_DB}
    ports:
      - "${PRODUCTS_PORT}:5002"
    depends_on:
      - sqlserver
    networks:
      - foodfast-net

  orders:
    build: ./orders
    container_name: orders_service
    environment:
      DB_HOST: localhost
      DB_PORT: 1433
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${ORDERS_DB}
    ports:
      - "${ORDERS_PORT}:5003"
    depends_on:
      - sqlserver
      - users
      - products
    networks:
      - foodfast-net

  payments:
    build: ./payments
    container_name: payments_service
    environment:
      DB_HOST: localhost
      DB_PORT: 1444
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${PAYMENTS_DB}
    ports:
      - "${PAYMENTS_PORT}:5004"
    depends_on:
      - sqlserver
      - orders
    networks:
      - foodfast-net

networks:
  foodfast-net:
    driver: bridge
