name: CI/CD FoodFast Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Users image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/foodfast-users:latest ./users
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/foodfast-users:latest

    - name: Build and push Products image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/foodfast-products:latest ./products
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/foodfast-products:latest

    - name: Build and push Orders image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/foodfast-orders:latest ./orders
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/foodfast-orders:latest

    - name: Build and push Payments image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/foodfast-payments:latest ./payments
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/foodfast-payments:latest
